In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import pickle

In [3]:
sizes = np.random.randint(500, 3500, 100)

In [4]:
sizes

array([ 838, 2552, 3494, 1101, 3133,  649, 2958, 3008,  936, 1331, 2379,
       3290, 1651, 1241,  942, 1140, 1478, 1126, 3380, 2533,  601, 1678,
        918, 1901,  721, 3421, 1222, 2051, 3040, 1277, 1474, 2612, 3242,
        899, 2996, 1566, 2400, 3465, 1294, 1897, 1181,  720, 3199, 2945,
       2141, 3188, 1771, 1214, 3206,  694,  615, 3436,  772,  762, 1150,
        641, 2783, 1466,  574, 2577, 1010, 2129, 2968, 2790, 2903,  697,
        729, 1165, 1844, 3070, 3437,  872, 3356, 1542, 3432, 2734, 1360,
        754, 1861, 1603, 1936, 1383, 2917, 2679, 2059, 1598,  500, 3008,
        619, 2167,  921,  603, 2727, 2445, 2944, 2757, 3146, 3074, 2971,
       1813])

In [5]:
bedrooms=np.random.randint(1,6,100)

In [6]:
bedrooms

array([2, 4, 4, 3, 4, 4, 4, 5, 4, 2, 2, 4, 3, 5, 4, 4, 2, 2, 4, 5, 5, 3,
       2, 1, 4, 4, 5, 3, 2, 1, 3, 5, 4, 2, 4, 1, 3, 5, 5, 5, 2, 5, 3, 2,
       1, 1, 3, 2, 1, 2, 5, 2, 2, 2, 5, 5, 4, 5, 5, 5, 2, 4, 3, 1, 4, 3,
       2, 4, 5, 3, 4, 2, 2, 3, 5, 5, 3, 5, 4, 4, 1, 5, 5, 4, 2, 1, 4, 3,
       3, 1, 1, 2, 1, 2, 4, 2, 2, 3, 3, 2])

In [7]:
prices=(sizes*0.3) + (bedrooms * 50) +np.random.randint(-200,200,100)

In [8]:
prices

array([ 307.4, 1074.6, 1319.2,  535.3, 1182.9,  310.7, 1105.4, 1081.4,
        578.8,  671.3,  654.7, 1246. ,  642.3,  819.3,  331.6,  567. ,
        717.4,  319.8, 1220. , 1087.9,  566.3,  571.4,  273.4,  572.3,
        357.3, 1235.3,  746.6,  720.3, 1145. ,  262.1,  559.2, 1177.6,
       1271.6,  386.7, 1244.8,  471.8,  725. , 1177.5,  446.2,  682.1,
        346.3,  614. , 1082.7, 1027.5,  804.3, 1089.4,  691.3,  485.2,
       1062.8,  278.2,  399.5, 1104.8,  439.6,  207.6,  498. ,  479.3,
       1104.9,  710.8,  541.2,  931.1,  305. ,  832.7,  994.4,  791. ,
       1188.9,  502.1,  479.7,  358.5,  978.2,  996. , 1307.1,  283.6,
        907.8,  693.6, 1178.6, 1029.2,  669. ,  425.2,  857.3,  679.9,
        498.8,  732.9, 1007.1, 1131.7,  765.7,  521.4,  538. , 1197.4,
        518.7,  855.1,  361.3,  103.9,  944.1,  901.5, 1252.2,  798.1,
       1142.8, 1039.2, 1007.3,  650.9])

In [11]:
data=pd.DataFrame(
    {
        "size_sqft":sizes,
        "bedrooms":bedrooms,
        "price":prices       
    }
)

In [12]:
data.head()

size_sqft  bedrooms   price
0        838         2   307.4
1       2552         4  1074.6
2       3494         4  1319.2
3       1101         3   535.3
4       3133         4  1182.9

In [13]:
x=data[["size_sqft","bedrooms"]]


In [14]:
y=data["price"]

In [15]:
model=LinearRegression()

In [17]:
model.fit(x,y)

LinearRegression()

In [18]:
sample_X= np.array([[200,3],[1500,2]])

In [19]:
model.predict(sample_X)

/home/mayur_chavda/ML/venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([218.2720285 , 550.67725538])

In [20]:
with open("house_price_model.pkl","wb") as f:
     pickle.dump(model,f)